first commit
mehmetozkn/spring-computer-store pull request #1
Opened 2023-08-15 11:03 UTC by mehmetozkn

BasketProductService sınıfındaki addProductToBasket methodu, parametre olarak AddProductRequest alır.
AddProductRequest user_id, product_id, basket_id ve quantity değerlerini içerir. 

Method product_id ile ürünü bulur, user_id ile kullancıyı bulur ve idsi basket_id olan bir sepet oluşturarak sepete quantity kadar ürün ekleme işlemini gerçekleştirir.

2023-08-15 12:06 UTC, mrtkrkrt commented
Test comment

2023-08-28 10:06 UTC, cakiciesranur requested changes

2023-08-28 10:06 UTC, cakiciesranur commented on mvnw
> +#!/bin/sh
bunu git ignore a ekleyelim.

2023-08-28 10:06 UTC, cakiciesranur commented on mvnw.cmd
> +@REM ----------------------------------------------------------------------------
bunu git ignore a ekleyelim.

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/MarketAppApplication.java
> +    private final UserRepository userRepository;
@requiredargsconstructor kullanarak yapalım bunları. diğer sınıfları da kontrol edip değiştirimisin?

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/MarketAppApplication.java
> +public class MarketAppApplication implements CommandLineRunner {
neden CommandLineRunner'ı implemente ediyoruz?

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/config/ModelMapperConfig.java
> +        ModelMapper modelMapper = new ModelMapper();
direkt retrun edebilrisin variable a tanımlamaya gerek yok.

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/dto/converter/BasketProductDtoConverter.java
> +        BasketProductDto basketProductDto = modelMapper.map(basketProduct, BasketProductDto.class);
direkt return edebiliriz.
return modelMapper.map(basketProduct, BasketProductDto.class);

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/dto/converter/UserDtoConverter.java
> +import com.marketapp.MarketApp.model.BasketProduct;
kullanılmayan importları kaldıralım. diğer sınıfları da kontrol edermisin?

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/controller/ProductController.java
> +        return ResponseEntity.ok(productService.deleteProduct(id));
silinen ürünü tekrar dönmek mantıklı değil gibi. neden döndük? Özel bir sebebi yoksa bu tarz bir respoınse dönebilrisin.Sadece örnek:
 return ResponseEntity.ok("Product is deleted successfully!");

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/controller/UserController.java
> +    @PutMapping("/update/{id}")
burda sadece bir alanı update etmek istediğimde tüm datayı update ediyorum sanırım.  partial update için belki putmapping yerine patchmapping kullanılabilir.Tabiki bu ihtiyaca göre karar verilecek bir durum ama userın sadece product listini update etmek istediğimde id ve liste yeterli olmalı bence. diğer alanlar ezilmemeli.

_**POST: is used to create an entity
PUT: is used to update/replace an existing entity where you must send the entire representation of the entity as you wish for it to be stored
PATCH: is used to update an entity where you send only the fields that need to be updated**_

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/service/BasketProductService.java
> +        BasketProduct basketProduct = user.getProductList().stream()
burda user ilk defa product ekliyorsa test edebilmişmiydin? user.getProductList() null  NPE almıyormu burda?

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/service/CommentService.java
> +                -> new RuntimeException("Could not find comment by id" + id));
RuntimeException yerine custom exception fırlatalım.

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/service/CommentService.java
> +        return new ArrayList<Comment>((Collection<? extends Comment>) commentRepository.findAll());
return (List<Comment>) commentRepository.findAll(); yapmak yeterli değil mi?  Birde diğer örneklerde db objelerini dto ya dönüşyütmüşsün burada direkt db objesi ile repsonse dönmüşsün. neden dto ya cevirmedik.

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/controller/CommentController.java
> +        return ResponseEntity.ok(commentService.deleteComment(id));
aynı sekilde burada da silinen obje yerine dilindiğine dair bilgi dönülmeli bence

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/service/ProductService.java
> +                .stream()
hiç product yoksa nasıl davranıyor. burada npe alıyormu? hiç product yoksa emply list dönmeli.

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/config/RedisConfig.java
> +    public RedisTemplate<?, ?> redisTemplate() {
burda key, Object seklinde cacheleyeceksen ?,? yerine <String, Object> yapılabilir.

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/config/RedisConfig.java
> +    public LettuceConnectionFactory redisConnectionFactory() {
LettuceConnectionFactory kullanmanın özel bir sebebi var mı? yoksa redisconnectionFactory kullnamak daha kolay bir secenek olacaktır. 
https://redis.com/blog/jedis-vs-lettuce-an-exploration/

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/config/RedisConfig.java
> +public class RedisConfig {
bunu projede herhangi bri yerde kullandık mı? ben mi kacırıdm

2023-08-28 10:06 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/config/SecurityConfig.java
> +        UserDetails user = User.withUsername("mehmet")
bu şekilde user bilgilerini vermek dogru değil diye konusmustuk. sonrasında da elinde referans olması acısından jwt token ile ilgili bir örnek bırakıyorum: https://www.codejava.net/frameworks/spring-boot/spring-security-jwt-authentication-tutorial

2023-08-28 10:06 UTC, cakiciesranur commented on docker-compose.yml
> +    container_name: computer_store
docker olmadıgı icin deneyemedim de bu calısıyormu? Enbvironment variable lar hiç tanımlanmamış docker-compose ta o nedenle soruyorum.

2023-08-28 10:13 UTC, cakiciesranur commented on src/main/java/com/marketapp/MarketApp/controller/AuthController.java
> +public class AuthController {
bu ne için kullanılıyor?

2023-09-10 19:36 UTC, merged